Initial working commit
stuvusIT/zfs-snap-manager-role pull request #1
Opened 2017-05-26 20:13 UTC by SlothOfAnarchy

- clones and installs the specified version of zfs-snap-manager
- creates the configuration file and restarts the zfs-snap-manager systemd service

2017-05-26 21:08 UTC, dasJ requested changes

2017-05-26 21:08 UTC, dasJ commented on README.md
> +| Name                  | mandatory | default |Description                                                                            |
Indent this table and capitalise mandatory

2017-05-26 21:08 UTC, dasJ commented on README.md
> +| `zfs_snapshot_defaults`      | no | {} | Default snapshot configuration used when there is no explicit configuration for a filesystem, see [snapshot configuration](#snapshot configuration) for cont
Make {} a blockquote

2017-05-26 21:08 UTC, dasJ commented on tasks/install.yml
> +- name: Create clone directory
Clone on the control machine instead of the target

2017-05-26 21:15 UTC, SlothOfAnarchy commented on README.md
> +| Name                  | mandatory | default |Description                                                                            |
I already did !?

2017-05-26 21:25 UTC, SlothOfAnarchy commented
please rereview

2017-05-27 13:22 UTC, dasJ requested changes
Stop deleting my comments. Clone on the control machine

2017-05-27 16:36 UTC, dasJ requested changes

2017-05-27 16:36 UTC, dasJ commented on tasks/install.yml
> +- name: create library directory
Capitalize

2017-05-27 16:36 UTC, dasJ commented on tasks/install.yml
> +- name: Create clone directory
Do you really need to do this?

2017-05-27 16:36 UTC, dasJ commented on tasks/install.yml
> +    src: "{{ zfs_snap_manager_clone_dir }}/python/src/github.com/khenderick/zfs-snap-manager/system/zfs-snap-manager.service"
Use a variable for this long path, it looks awfully copied down

2017-05-28 11:32 UTC, SlothOfAnarchy commented on tasks/install.yml
> +- name: Create clone directory
no.

2017-05-28 11:33 UTC, SlothOfAnarchy commented
please rereview and take #2 into consideration.

2017-06-04 22:37 UTC, dasJ requested changes

2017-06-04 22:37 UTC, dasJ commented on README.md
> +| Name                         | mandatory | default                  | Description
Fix the indentation and capitalize The headings

2017-06-04 22:37 UTC, dasJ commented on README.md
> +Obviously, any ZFS filesystems that should be snapshotted must exist.
Is a special distribution required?

2017-06-04 22:37 UTC, dasJ commented on README.md
> +| Name                   | Default     | Description
This table doesn't look good either

2017-06-04 22:37 UTC, dasJ commented on README.md
> +zfs_parent_fs: rpool
Why not namespace the variables?

2017-06-04 22:37 UTC, dasJ commented on defaults/main.yml
> +global_cache_dir: "{{ ansible_env.HOME }}/.cache"
Please do not use this default, use the `mandatory` filter instead

2017-06-04 22:37 UTC, dasJ commented on tasks/install.yml
> +    zfs_snap_manager_clone_dir: "{{ global_cache_dir }}/python/src/github.com/khenderick/zfs-snap-manager"
Why not use `vars/main.yml` so you don't have to use this task?

2017-06-04 22:37 UTC, dasJ commented on tasks/install.yml
> +    mode: 0755
Why not `750`?

2017-06-04 22:38 UTC, dasJ commented
@SlothOfAnarchy Also delegate the clone task to `localhost`

2017-06-04 22:43 UTC, SlothOfAnarchy commented on README.md
> +zfs_parent_fs: rpool
They are.

2017-06-04 22:44 UTC, SlothOfAnarchy commented on README.md
> +| Name                         | mandatory | default                  | Description
I don't think it's all that important.

2017-08-10 22:57 UTC, SlothOfAnarchy commented
please rereview @dasJ

2017-08-11 10:14 UTC, SlothOfAnarchy commented
local cloning is now included (#2)

2017-08-16 16:59 UTC, dasJ requested changes

2017-08-16 16:59 UTC, dasJ commented on README.md
> +`python2` has to be installed on the target machine. Obviously, any ZFS filesystems that should be snapshotted must exist.
Why not install it with this role?

2017-08-16 16:59 UTC, dasJ commented on README.md
> +The machine that executes the playbook needs to have internet access as well as `git` installed.
Why don't you just install git? "The control machine needs to have internet access and needs to have git installed if it's not a Debian-based distribution"

2017-08-16 16:59 UTC, dasJ commented on README.md
> +| Name                         | Mandatory / Default      | Description                                                                             |
Another unindented table

2017-08-16 16:59 UTC, dasJ commented on README.md
> +| `zvols`                      | `[]`                     | List of zvols to be snapshotted. Snapshots can be configured using the dict item `snapshots`. For its content see [snapshot configuration](
Why is `zvols` not prefixed?

2017-08-16 16:59 UTC, dasJ commented on tasks/install.yml
> +  notify: Enable and restart zfs-snap-manager
Reload systemd if this changed

2017-08-16 22:32 UTC, SlothOfAnarchy commented on README.md
> +The machine that executes the playbook needs to have internet access as well as `git` installed.
I can't possible know which obscure distribution the executing machine is running. I don't want to add tasks for this, especially as `git` it is a very common tool, which in most cases will be used to clone this repository in the first place.

2017-08-16 22:37 UTC, SlothOfAnarchy commented on README.md
> +| `zvols`                      | `[]`                     | List of zvols to be snapshotted. Snapshots can be configured using the dict item `snapshots`. For its content see [snapshot configuration](
Is `zvols` a common abbreviation or parameter outside of the ZFS context? I think it is unique enough.

2017-08-16 22:45 UTC, SlothOfAnarchy commented on README.md
> +| Name                         | Mandatory / Default      | Description                                                                             |
I don't care.

2017-08-20 14:04 UTC, dasJ approved these changes
I guess

2017-08-20 14:04 UTC, merged